// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-subscribers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-subscribers.ts
var search_subscribers_default = defineTool({
  name: "search_subscribers",
  title: "Search subscribers",
  description: "Search cable/internet subscribers by name, subscriber ID or mobile number. Returns id, subscriber ID, name, mobile, region, status and balances.",
  inputSchema: {
    query: z.string().trim().describe("Name, subscriber ID or mobile number fragment. Empty for a general list."),
    status: z.enum(["all", "active", "inactive", "prospect", "archived"]).default("all").describe("Filter by customer status."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("subscribers").select("id, subscriber_id, name, mobile, region, customer_status, cable_balance, internet_balance, services").order("name").limit(limit);
    if (query) {
      const like = `%${query.replace(/[%,]/g, "")}%`;
      q = q.or(`name.ilike.${like},subscriber_id.ilike.${like},mobile.ilike.${like}`);
    }
    if (status !== "all") q = q.eq("customer_status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { subscribers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-subscriber.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_subscriber_default = defineTool2({
  name: "get_subscriber",
  title: "Get subscriber profile",
  description: "Full profile for one subscriber: contact details, balances, subscriptions, paired devices and open complaints. Accepts the human subscriber ID (e.g. MAHARAJ-003) or the internal UUID.",
  inputSchema: {
    subscriber_id: z2.string().trim().min(1).describe("Human subscriber ID or internal UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subscriber_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(subscriber_id);
    const { data: subscriber, error } = await supabase.from("subscribers").select("*").eq(isUuid ? "id" : "subscriber_id", subscriber_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!subscriber) {
      return { content: [{ type: "text", text: `No subscriber found for "${subscriber_id}"` }], isError: true };
    }
    const [subs, devices, complaints] = await Promise.all([
      supabase.from("subscriptions").select("id, service_type, pack_name_snapshot, pack_price_snapshot, start_date, end_date, status, total_charged").eq("subscriber_id", subscriber.id).order("start_date", { ascending: false }).limit(20),
      supabase.from("stb_inventory").select("id, serial_number, vc_id, device_type, service_type, status").eq("subscriber_id", subscriber.id),
      supabase.from("complaints").select("id, date, category, priority, status, description").eq("subscriber_id", subscriber.id).order("date", { ascending: false }).limit(10)
    ]);
    const firstError = subs.error ?? devices.error ?? complaints.error;
    if (firstError) return { content: [{ type: "text", text: firstError.message }], isError: true };
    const profile = {
      subscriber: {
        id: subscriber.id,
        subscriber_id: subscriber.subscriber_id,
        name: subscriber.name,
        mobile: subscriber.mobile,
        region: subscriber.region,
        services: subscriber.services,
        customer_status: subscriber.customer_status,
        join_date: subscriber.join_date,
        cable_balance: subscriber.cable_balance,
        internet_balance: subscriber.internet_balance
      },
      subscriptions: subs.data ?? [],
      devices: devices.data ?? [],
      complaints: complaints.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-expiring-subscriptions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_expiring_subscriptions_default = defineTool3({
  name: "list_expiring_subscriptions",
  title: "List expiring subscriptions",
  description: "Active subscriptions ending within the next N days, oldest expiry first. Use for renewal follow-up lists.",
  inputSchema: {
    days: z3.number().int().min(0).max(90).default(7).describe("Look-ahead window in days."),
    limit: z3.number().int().min(1).max(100).default(50).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const today = /* @__PURE__ */ new Date();
    const until = new Date(today.getTime() + days * 864e5);
    const iso = (d) => d.toISOString().slice(0, 10);
    const { data, error } = await supabase.from("subscriptions").select("id, subscriber_id, service_type, pack_name_snapshot, pack_price_snapshot, start_date, end_date, status").eq("status", "active").gte("end_date", iso(today)).lte("end_date", iso(until)).order("end_date").limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = Array.from(new Set((data ?? []).map((r) => r.subscriber_id)));
    const names = /* @__PURE__ */ new Map();
    if (ids.length) {
      const { data: people, error: peopleError } = await supabase.from("subscribers").select("id, subscriber_id, name, mobile").in("id", ids);
      if (peopleError) return { content: [{ type: "text", text: peopleError.message }], isError: true };
      for (const p of people ?? []) names.set(p.id, { subscriber_id: p.subscriber_id, name: p.name, mobile: p.mobile });
    }
    const rows = (data ?? []).map((r) => ({ ...r, subscriber: names.get(r.subscriber_id) ?? null }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { expiring: rows }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool4({
  name: "list_transactions",
  title: "List transactions",
  description: "Recent ledger transactions (payments, charges, refunds) across the business or for one subscriber, newest first.",
  inputSchema: {
    from_date: z4.string().trim().default("").describe("Start date YYYY-MM-DD. Empty for no lower bound."),
    to_date: z4.string().trim().default("").describe("End date YYYY-MM-DD. Empty for no upper bound."),
    subscriber_uuid: z4.string().trim().default("").describe("Internal subscriber UUID to filter by. Empty for all."),
    type: z4.string().trim().default("").describe("Transaction type filter, e.g. payment or charge. Empty for all."),
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, subscriber_uuid, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("transactions").select("id, date, subscriber_id, type, amount, service_type, payment_method, status, description").order("date", { ascending: false }).limit(limit);
    if (from_date) q = q.gte("date", from_date);
    if (to_date) q = q.lte("date", to_date);
    if (subscriber_uuid) q = q.eq("subscriber_id", subscriber_uuid);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((sum, r) => sum + Number(r.amount ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, total, rows: data ?? [] }, null, 2) }],
      structuredContent: { count: data?.length ?? 0, total, rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-packs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_packs_default = defineTool5({
  name: "list_packs",
  title: "List packs",
  description: "Available cable/internet packs with price, validity and provider cost.",
  inputSchema: {
    service_type: z5.enum(["all", "cable", "internet"]).default("all").describe("Filter packs by service type."),
    active_only: z5.boolean().default(true).describe("Only return packs currently on sale.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ service_type, active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("packs").select("id, name, service_type, price, provider_cost, validity_days, billing_type, channels, is_active").order("name");
    if (service_type !== "all") q = q.eq("service_type", service_type);
    if (active_only) q = q.eq("is_active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { packs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-devices.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_devices_default = defineTool6({
  name: "list_devices",
  title: "List devices",
  description: "Set-top boxes, ONUs and routers in inventory with status, serial number, VC id and current assignment.",
  inputSchema: {
    status: z6.string().trim().default("").describe("Inventory status filter, e.g. available, assigned, faulty. Empty for all."),
    query: z6.string().trim().default("").describe("Serial number or VC id fragment. Empty for all."),
    limit: z6.number().int().min(1).max(100).default(50).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("stb_inventory").select("id, serial_number, vc_id, mac_address, device_type, service_type, status, subscriber_id, notes").order("serial_number").limit(limit);
    if (status) q = q.eq("status", status);
    if (query) {
      const like = `%${query.replace(/[%,]/g, "")}%`;
      q = q.or(`serial_number.ilike.${like},vc_id.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { devices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/business-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^3.25.76";
var business_summary_default = defineTool7({
  name: "business_summary",
  title: "Business summary",
  description: "Snapshot of the operation: subscriber counts by status, active subscriptions, outstanding balances, collections over a recent window and open complaints.",
  inputSchema: {
    days: z7.number().int().min(1).max(90).default(30).describe("Collection window in days.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - days * 864e5).toISOString().slice(0, 10);
    const [people, activeSubs, payments, openComplaints] = await Promise.all([
      supabase.from("subscribers").select("customer_status, cable_balance, internet_balance"),
      supabase.from("subscriptions").select("id", { count: "exact", head: true }).eq("status", "active"),
      supabase.from("transactions").select("amount, type, status").gte("date", since),
      supabase.from("complaints").select("id", { count: "exact", head: true }).neq("status", "resolved")
    ]);
    const firstError = people.error ?? activeSubs.error ?? payments.error ?? openComplaints.error;
    if (firstError) return { content: [{ type: "text", text: firstError.message }], isError: true };
    const byStatus = {};
    let outstanding = 0;
    let credit = 0;
    for (const p of people.data ?? []) {
      byStatus[p.customer_status] = (byStatus[p.customer_status] ?? 0) + 1;
      const bal = Number(p.cable_balance ?? 0) + Number(p.internet_balance ?? 0);
      if (bal > 0) outstanding += bal;
      else credit += -bal;
    }
    const collected = (payments.data ?? []).filter((t) => t.type === "payment" && t.status !== "voided").reduce((sum, t) => sum + Number(t.amount ?? 0), 0);
    const summary = {
      window_days: days,
      subscribers_total: people.data?.length ?? 0,
      subscribers_by_status: byStatus,
      active_subscriptions: activeSubs.count ?? 0,
      outstanding_dues: outstanding,
      customer_credit: credit,
      collected_in_window: collected,
      open_complaints: openComplaints.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zjlpmnlfbhhypfuzipvv";
var mcp_default = defineMcp({
  name: "cable-subscriber-manager",
  title: "Cable Subscriber Manager",
  version: "0.1.0",
  instructions: "Read-only tools for a cable TV / internet operator's subscriber book. Use `search_subscribers` to find a customer, `get_subscriber` for their full profile (subscriptions, devices, complaints), `list_expiring_subscriptions` for renewal follow-ups, `list_transactions` for the payment ledger, `list_packs` and `list_devices` for the catalog and inventory, and `business_summary` for an overall snapshot. All data is scoped to the signed-in operator.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_subscribers_default,
    get_subscriber_default,
    list_expiring_subscriptions_default,
    list_transactions_default,
    list_packs_default,
    list_devices_default,
    business_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
