
-- Phase 3.7 — first-class 'adjustment' transaction type (INV/D7)

-- 1) Extend the type CHECK constraint
ALTER TABLE public.transactions
  DROP CONSTRAINT IF EXISTS transactions_type_check;

ALTER TABLE public.transactions
  ADD CONSTRAINT transactions_type_check
  CHECK (type = ANY (ARRAY['payment'::text, 'charge'::text, 'refund'::text, 'adjustment'::text]));

-- 2) Recalc balance: adjustment behaves like a credit (reduces what subscriber owes),
--    but is NOT counted as cash. Reports split via type.
CREATE OR REPLACE FUNCTION public.recalc_subscriber_balance(p_subscriber_id uuid, p_service_type text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_balance numeric := 0;
  v_col text;
BEGIN
  IF p_subscriber_id IS NULL THEN RETURN; END IF;

  SELECT COALESCE(SUM(
    CASE
      WHEN type = 'charge'     THEN amount
      WHEN type = 'payment'    THEN -amount
      WHEN type = 'refund'     THEN amount
      WHEN type = 'adjustment' THEN -amount   -- credit by default
      ELSE 0
    END
  ), 0)
  INTO v_balance
  FROM public.transactions
  WHERE subscriber_id = p_subscriber_id
    AND COALESCE(service_type, 'cable') = p_service_type
    AND status NOT IN ('voided', 'reversal');

  v_col := CASE p_service_type WHEN 'internet' THEN 'internet_balance' ELSE 'cable_balance' END;

  EXECUTE format('UPDATE public.subscribers SET %I = $1 WHERE id = $2', v_col)
    USING v_balance, p_subscriber_id;
END;
$function$;

-- 3) Void: an adjustment credit is reversed by an offsetting 'charge' row
--    (mirrors payment→charge mapping). Keeps the void chain symmetric.
CREATE OR REPLACE FUNCTION public.void_transaction(p_transaction_id uuid, p_reason_code void_reason_code, p_reason text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_orig public.transactions;
  v_reversal_id uuid;
  v_opposite_type text;
  v_reason text;
  v_reason_label text;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF p_reason_code IS NULL THEN
    RAISE EXCEPTION 'A reason code is required to void a transaction';
  END IF;
  v_reason := btrim(COALESCE(p_reason, ''));

  SELECT * INTO v_orig
    FROM public.transactions
   WHERE id = p_transaction_id
     AND user_id = v_uid
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaction not found or not owned by current user';
  END IF;

  IF v_orig.status <> 'posted' THEN
    RAISE EXCEPTION 'Only posted transactions can be voided (current status: %)', v_orig.status;
  END IF;

  IF v_orig.source IN ('subscription_charge','subscription_refund','reversal') THEN
    RAISE EXCEPTION 'This transaction was generated by a subscription action (source=%). Undo it through the subscription lifecycle (cancel / refund) instead of voiding the ledger row directly.', v_orig.source
      USING ERRCODE = 'check_violation';
  END IF;

  v_opposite_type := CASE v_orig.type
    WHEN 'payment'    THEN 'charge'
    WHEN 'charge'     THEN 'payment'
    WHEN 'refund'     THEN 'charge'
    WHEN 'adjustment' THEN 'charge'   -- adjustment credit reversed by an offsetting debit
    ELSE v_orig.type
  END;

  v_reason_label := replace(p_reason_code::text, '_', ' ');

  INSERT INTO public.transactions (
    user_id, subscriber_id, type, amount,
    description, date, service_type, provider_id,
    status, reverses_transaction_id,
    void_reason, void_reason_code, source
  ) VALUES (
    v_orig.user_id, v_orig.subscriber_id, v_opposite_type, v_orig.amount,
    'Reversal — ' || v_reason_label || CASE WHEN v_reason <> '' THEN ' (' || v_reason || ')' ELSE '' END,
    now(), v_orig.service_type, v_orig.provider_id,
    'reversal', v_orig.id,
    NULLIF(v_reason, ''), p_reason_code, 'reversal'
  )
  RETURNING id INTO v_reversal_id;

  UPDATE public.transactions
     SET status = 'voided',
         void_reason = NULLIF(v_reason, ''),
         void_reason_code = p_reason_code,
         voided_by = v_uid,
         voided_at = now()
   WHERE id = v_orig.id;

  RETURN v_reversal_id;
END;
$function$;
